/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using AI.Enterprise.Integration.RestApi.Client;
using AI.Enterprise.Integration.RestApi.Model;

namespace AI.Enterprise.Integration.RestApi.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDiagnosticControllerApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// getComponentsStatus
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ComponentsStatus</returns>
        ComponentsStatus GetComponentsStatusUsingGET ();

        /// <summary>
        /// getComponentsStatus
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ComponentsStatus</returns>
        ApiResponse<ComponentsStatus> GetComponentsStatusUsingGETWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectName"> (optional)</param>
        /// <returns>Guid</returns>
        Guid GetProject (string projectName = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectName"> (optional)</param>
        /// <returns>ApiResponse of Guid</returns>
        ApiResponse<Guid> GetProjectWithHttpInfo (string projectName = default(string));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// getComponentsStatus
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ComponentsStatus</returns>
        System.Threading.Tasks.Task<ComponentsStatus> GetComponentsStatusUsingGETAsync ();

        /// <summary>
        /// getComponentsStatus
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ComponentsStatus)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComponentsStatus>> GetComponentsStatusUsingGETAsyncWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectName"> (optional)</param>
        /// <returns>Task of Guid</returns>
        System.Threading.Tasks.Task<Guid> GetProjectAsync (string projectName = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectName"> (optional)</param>
        /// <returns>Task of ApiResponse (Guid)</returns>
        System.Threading.Tasks.Task<ApiResponse<Guid>> GetProjectAsyncWithHttpInfo (string projectName = default(string));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DiagnosticControllerApi : IDiagnosticControllerApi
    {
        private AI.Enterprise.Integration.RestApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DiagnosticControllerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DiagnosticControllerApi(String basePath)
        {
            this.Configuration = new AI.Enterprise.Integration.RestApi.Client.Configuration { BasePath = basePath };

            ExceptionFactory = AI.Enterprise.Integration.RestApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DiagnosticControllerApi"/> class
        /// </summary>
        /// <returns></returns>
        public DiagnosticControllerApi()
        {
            this.Configuration = AI.Enterprise.Integration.RestApi.Client.Configuration.Default;

            ExceptionFactory = AI.Enterprise.Integration.RestApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DiagnosticControllerApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DiagnosticControllerApi(AI.Enterprise.Integration.RestApi.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = AI.Enterprise.Integration.RestApi.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = AI.Enterprise.Integration.RestApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AI.Enterprise.Integration.RestApi.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AI.Enterprise.Integration.RestApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// getComponentsStatus 
        /// </summary>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ComponentsStatus</returns>
        public ComponentsStatus GetComponentsStatusUsingGET ()
        {
             ApiResponse<ComponentsStatus> localVarResponse = GetComponentsStatusUsingGETWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// getComponentsStatus 
        /// </summary>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ComponentsStatus</returns>
        public ApiResponse<ComponentsStatus> GetComponentsStatusUsingGETWithHttpInfo ()
        {

            var localVarPath = "/api/diagnostic/check";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetComponentsStatusUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsStatus>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsStatus) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsStatus)));
        }

        /// <summary>
        /// getComponentsStatus 
        /// </summary>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ComponentsStatus</returns>
        public async System.Threading.Tasks.Task<ComponentsStatus> GetComponentsStatusUsingGETAsync ()
        {
             ApiResponse<ComponentsStatus> localVarResponse = await GetComponentsStatusUsingGETAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// getComponentsStatus 
        /// </summary>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ComponentsStatus)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ComponentsStatus>> GetComponentsStatusUsingGETAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/diagnostic/check";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetComponentsStatusUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsStatus>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsStatus) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsStatus)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectName"> (optional)</param>
        /// <returns>Guid</returns>
        public Guid GetProject (string projectName = default(string))
        {
             ApiResponse<Guid> localVarResponse = GetProjectWithHttpInfo(projectName);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectName"> (optional)</param>
        /// <returns>ApiResponse of Guid</returns>
        public ApiResponse<Guid> GetProjectWithHttpInfo (string projectName = default(string))
        {

            var localVarPath = "/api/diagnostic/project";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (projectName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "projectName", projectName)); // query parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetProject", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Guid>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Guid) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Guid)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectName"> (optional)</param>
        /// <returns>Task of Guid</returns>
        public async System.Threading.Tasks.Task<Guid> GetProjectAsync (string projectName = default(string))
        {
             ApiResponse<Guid> localVarResponse = await GetProjectAsyncWithHttpInfo(projectName);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="AI.Enterprise.Integration.RestApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectName"> (optional)</param>
        /// <returns>Task of ApiResponse (Guid)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Guid>> GetProjectAsyncWithHttpInfo (string projectName = default(string))
        {

            var localVarPath = "/api/diagnostic/project";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (projectName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "projectName", projectName)); // query parameter

            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetProject", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Guid>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Guid) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Guid)));
        }

    }
}
