@startuml
actor User
participant adminPage.jsp
participant BS.PasswordFormSaver
participant BS.FormSaver
participant BS.AbstractWebForm
participant BS
== Load page ==
User -> adminPage.jsp : GET
create GlobalConnectionSettingsForm
adminPage.jsp -> GlobalConnectionSettingsForm : new
create PtaiConnectionSettingsForm
GlobalConnectionSettingsForm -> PtaiConnectionSettingsForm : new
adminPage.jsp -> GlobalConnectionSettingsForm : setupEventHandlers
== Test connection ==
User -> adminPage.jsp : POST
adminPage.jsp -> GlobalConnectionSettingsForm : save
activate GlobalConnectionSettingsForm
GlobalConnectionSettingsForm -> PtaiConnectionSettingsForm : save
create Listener
PtaiConnectionSettingsForm -> Listener : createErrorListener
PtaiConnectionSettingsForm -> BS.PasswordFormSaver : save
BS.PasswordFormSaver -> Listener : set onPublicKeyExpiredError
BS.PasswordFormSaver -> BS.FormSaver : save
BS.FormSaver -> Listener : onBeginSave
BS.FormSaver -> PtaiConnectionSettingsForm : serializeParameters
activate PtaiConnectionSettingsForm
PtaiConnectionSettingsForm -> BS.AbstractWebForm : serializeParameters
activate BS.AbstractWebForm
BS.AbstractWebForm --> PtaiConnectionSettingsForm : params
deactivate BS.AbstractWebForm
PtaiConnectionSettingsForm --> BS.FormSaver : params
deactivate PtaiConnectionSettingsForm
BS.FormSaver -> BS : ajaxRequest(params)
BS -> Listener : onCompleteSave
Listener -> BS.TestConnectionDialog : show
@enduml