@startuml

package auth {
    abstract class Auth {
    }
    class CredentialsAuth {
      userName
      password
    }
    class NoneAuth
    class TokenAuth {
      userName
      apiToken
    }
    Auth <|-up- CredentialsAuth
    Auth <|-up- NoneAuth
    Auth <|-up- TokenAuth
}

class LegacyCredentials {
    clientCertificate
    clientKey
    serverCaCertificates
}

class SlimCredentials {
    userName
    password
    serverCaCertificates
}

package globalconfig {
    class BaseConfig {
        configName
    }
    class LegacyConfig
    class SlimConfig
    LegacyConfig -up-|> BaseConfig
    SlimConfig -up-|> BaseConfig
}

package localconfig {
    class ConfigBase {
    }
    class ConfigGlobal {
        configName
    }
    class ConfigLegacyCustom {
    }
    class ConfigSlimCustom {
    }
    ConfigGlobal -up-|> ConfigBase
    ConfigLegacyCustom -down-|> ConfigBase
    ConfigSlimCustom -down-|> ConfigBase
}

package scansettings {
    class ScanSettings {
    }
    class ScanSettingsManual {
        jsonSettings
        jsonPolicy
    }
    class ScanSettingsUi {
        projectName
    }
    ScanSettingsManual -up-|> ScanSettings
    ScanSettingsUi -up-|> ScanSettings
}

package serversettings {
    class LegacyServerSettings {
        serverUrl
        jenkinsServerUrl
        jenkinsJobName
        jenkinsMaxRetry
        jenkinsRetryDelay
    }
    LegacyServerSettings -left-> LegacyCredentials : serverCredentials
    LegacyServerSettings ----> "jenkinsServerCredentials" Auth

    class SlimServerSettings {
        serverUrl
    }
    SlimServerSettings -right-> SlimCredentials : serverCredentials
    'LegacyServerSettings -[hidden]- SlimServerSettings
}

ConfigSlimCustom -up--> SlimServerSettings : slimServerSettings
ConfigLegacyCustom -up--> LegacyServerSettings : legacyServerSettings

LegacyConfig --> LegacyServerSettings : legacyServerSettings
SlimConfig --> SlimServerSettings : slimServerSettings

class Plugin
class Transfer

Plugin -down-> ScanSettings : scanSettings
Plugin -up-> ConfigBase : config
Plugin -right-> Transfer : transfers[]

@enduml