@startuml

class globalManagementPolicy

class bootstrapToken

class serverConfig <<json>>

bootstrapToken ---> "acl / tokens / master" serverConfig
bootstrapToken --> globalManagementPolicy

class agentPolicy
note left: "node "consul-server-one" {\n    policy = "write"\n}"

class agentToken
agentToken --> agentPolicy
agentToken ---> "acl / tokens / agent" serverConfig

@enduml
