@startuml
(*) --> "Create OAuth client"
if "Check if Jwt exist" then
  -->[true] "Refresh access token"
  -->"Authenticate using client id/secret and refresh_token"
  if "Success" then
    -->[true] (*)

  else
    --> "Authenticate using client id/secret and user name/password"
    -->(*)
  endif
else
  --> "Acquire access token"
  --> "Authenticate using client id/secret and user name/password"
endif
@enduml