@startuml
Plugin -> "PTAI projectManagement": POST /api/Projects/createProject
note left: Если проект еще не существует
Plugin -> "PTAI filesStore": POST /api/Store/sources/{projectId}
note left: Загрузка сканируемых артефактов
Plugin -> "PTAI ciApi": POST /api/jobBuild/{projectName}
note left: Запуск анализа
loop
Plugin -> "PTAI ciApi": GET /api/jobBuild/{projectName}
"PTAI ciApi" --> Plugin: SAST status
Plugin -> "PTAI ciApi": GET /api/jobProgressiveText/{projectName}
"PTAI ciApi" --> Plugin: SAST log
end
Plugin -> "PTAI ciApi": GET /api/jobBuildArtifact/{projectName}
note left: Получить результаты анализа
"PTAI ciApi" --> Plugin: SAST JSON / HTML result files
@enduml
