@startuml
class manifest {
    id
    name
    version
    publisher
    description
    categories["Build and release"]
    tags["Security", "SCA", "Static Code Analysis" ...]
    scopes["vso.build_execute"]
}

class target {
    id = "Microsoft.VisualStudio.Services"
}

class icon {
    default
}

class content
class details {
    path
}
class license {
    path
}
content --> details
content --> license

class link {
    uri
}

class links
links --> link : getstarted
links --> link : learn
links --> link : support

class file {
    path
    addressable
    packagePath
}

class contribution {
    id
    type
    targets[]
}



manifest --> target : targets
manifest --> icon : icons
manifest --> content
manifest --> links
manifest --> file : files
manifest --> contribution : contributions[]

@enduml
