/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AI.Enterprise.Integration.RestApi.Api;
using AI.Enterprise.Integration.RestApi.Model;
using AI.Enterprise.Integration.RestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AI.Enterprise.Integration.RestApi.Test
{
    /// <summary>
    ///  Class for testing ComponentsStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComponentsStatusTests
    {
        // TODO uncomment below to declare an instance variable for ComponentsStatus
        //private ComponentsStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComponentsStatus
            //instance = new ComponentsStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComponentsStatus
        /// </summary>
        [Test]
        public void ComponentsStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ComponentsStatus
            //Assert.IsInstanceOf(typeof(ComponentsStatus), instance);
        }


        /// <summary>
        /// Test the property 'Ptai'
        /// </summary>
        [Test]
        public void PtaiTest()
        {
            // TODO unit test for the property 'Ptai'
        }
        /// <summary>
        /// Test the property 'Embedded'
        /// </summary>
        [Test]
        public void EmbeddedTest()
        {
            // TODO unit test for the property 'Embedded'
        }

    }

}
