/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AI.Enterprise.Integration.RestApi.Api;
using AI.Enterprise.Integration.RestApi.Model;
using AI.Enterprise.Integration.RestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AI.Enterprise.Integration.RestApi.Test
{
    /// <summary>
    ///  Class for testing ComponentStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComponentStatusTests
    {
        // TODO uncomment below to declare an instance variable for ComponentStatus
        //private ComponentStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComponentStatus
            //instance = new ComponentStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComponentStatus
        /// </summary>
        [Test]
        public void ComponentStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ComponentStatus
            //Assert.IsInstanceOf(typeof(ComponentStatus), instance);
        }



    }

}
