/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AI.Enterprise.Integration.RestApi.Api;
using AI.Enterprise.Integration.RestApi.Model;
using AI.Enterprise.Integration.RestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AI.Enterprise.Integration.RestApi.Test
{
    /// <summary>
    ///  Class for testing JobState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobStateTests
    {
        // TODO uncomment below to declare an instance variable for JobState
        //private JobState instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JobState
            //instance = new JobState();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JobState
        /// </summary>
        [Test]
        public void JobStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" JobState
            //Assert.IsInstanceOf(typeof(JobState), instance);
        }


        /// <summary>
        /// Test the property 'Log'
        /// </summary>
        [Test]
        public void LogTest()
        {
            // TODO unit test for the property 'Log'
        }
        /// <summary>
        /// Test the property 'Pos'
        /// </summary>
        [Test]
        public void PosTest()
        {
            // TODO unit test for the property 'Pos'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
