/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AI.Enterprise.Integration.RestApi.Api;
using AI.Enterprise.Integration.RestApi.Model;
using AI.Enterprise.Integration.RestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AI.Enterprise.Integration.RestApi.Test
{
    /// <summary>
    ///  Class for testing ResponseEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseEntityTests
    {
        // TODO uncomment below to declare an instance variable for ResponseEntity
        //private ResponseEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseEntity
            //instance = new ResponseEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseEntity
        /// </summary>
        [Test]
        public void ResponseEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ResponseEntity
            //Assert.IsInstanceOf(typeof(ResponseEntity), instance);
        }


        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'StatusCodeValue'
        /// </summary>
        [Test]
        public void StatusCodeValueTest()
        {
            // TODO unit test for the property 'StatusCodeValue'
        }

    }

}
