@startuml
hide footbox
actor Browser
Browser -> AstAdminPage : fillModel
activate AstAdminPage
participant settings
create BasePropertiesBean
AstAdminPage -> BasePropertiesBean : new
AstAdminPage -> settings : forEach
activate settings
settings -> BasePropertiesBean : setProperty
deactivate settings
participant model
AstAdminPage -> model : put("propertesBean", BasePropertiesBean)
AstAdminPage -> model : put("hexEncodedPublicKey", key)
deactivate AstAdminPage
@enduml