/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AI.Enterprise.Integration.RestApi.Client.OpenAPIDateConverter;

namespace AI.Enterprise.Integration.RestApi.Model
{
    /// <summary>
    /// ComponentsStatus
    /// </summary>
    [DataContract]
    public partial class ComponentsStatus :  IEquatable<ComponentsStatus>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Ptai
        /// </summary>
        [DataMember(Name="ptai", EmitDefaultValue=false)]
        public ComponentStatus? Ptai { get; set; }
        /// <summary>
        /// Gets or Sets Embedded
        /// </summary>
        [DataMember(Name="embedded", EmitDefaultValue=false)]
        public ComponentStatus? Embedded { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ComponentsStatus" /> class.
        /// </summary>
        /// <param name="ptai">ptai.</param>
        /// <param name="embedded">embedded.</param>
        public ComponentsStatus(ComponentStatus ptai = default(ComponentStatus), ComponentStatus embedded = default(ComponentStatus))
        {
            this.Ptai = ptai;
            this.Embedded = embedded;
        }
        


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ComponentsStatus {\n");
            sb.Append("  Ptai: ").Append(Ptai).Append("\n");
            sb.Append("  Embedded: ").Append(Embedded).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ComponentsStatus);
        }

        /// <summary>
        /// Returns true if ComponentsStatus instances are equal
        /// </summary>
        /// <param name="input">Instance of ComponentsStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ComponentsStatus input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Ptai == input.Ptai ||
                    (this.Ptai != null &&
                    this.Ptai.Equals(input.Ptai))
                ) && 
                (
                    this.Embedded == input.Embedded ||
                    (this.Embedded != null &&
                    this.Embedded.Equals(input.Embedded))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Ptai != null)
                    hashCode = hashCode * 59 + this.Ptai.GetHashCode();
                if (this.Embedded != null)
                    hashCode = hashCode * 59 + this.Embedded.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
