/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AI.Enterprise.Integration.RestApi.Client.OpenAPIDateConverter;

namespace AI.Enterprise.Integration.RestApi.Model
{
    /// <summary>
    /// Defines ComponentStatus
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ComponentStatus
    {
        /// <summary>
        /// Enum FAILURE for value: FAILURE
        /// </summary>
        [EnumMember(Value = "FAILURE")]
        FAILURE = 1,

        /// <summary>
        /// Enum SUCCESS for value: SUCCESS
        /// </summary>
        [EnumMember(Value = "SUCCESS")]
        SUCCESS = 2

    }

}
