@startuml
node dc.domain.org {
}

node docker.domain.org {
    [ci]
    [gogs]
    [nginx]
    [consul-docker]
    [portainer]
    [ptai-integration-service]
    [ptai-integration-service] --> [consul-docker]
}

node ptai.domain.org {
    [consul-ptai]
    [ci-sast-agent]
    [ptai]
    [ptai-agent]
    [ci-sast-agent] ..> [ptai-agent]
}

[consul-docker] ..> [consul-ptai]
[ptai-integration-service] --> [ci-sast-agent]
[ptai-integration-service] --> [ptai]
[ptai-agent] --> [ptai]

@enduml