@startuml

frame keystore.jks {
    [ptai ssl client certificate and key]
    [integration service certificate and key]
    [embedded authz service certificate and key]
    [root ca certificate]
    [intermediate ca certificate]
    [embedded authz service certificate and key] -[hidden]down- [root ca certificate]
    [embedded authz service certificate and key] -[hidden]down- [intermediate ca certificate]
}

frame application.yml {
    [server.ssl.keystore]
    [server.ssl.keystore-password]
    [server.ssl.key-alias]
    [server.ssl.key-password]
    [server.ssl.truststore]
    [server.ssl.truststore-password]
    [ptai-backend-services.ptai-key-alias]
    [ptai-backend-services.ptai-key-password]
    [ptai-authorization-server.sign-key-alias]
    [ptai-authorization-server.sign-key-password]
    [ptai-integration-service.check-cert-alias]
}

[server.ssl.keystore] --> keystore.jks
[server.ssl.keystore-password] --> keystore.jks
[server.ssl.key-alias] --> [integration service certificate and key]
[server.ssl.key-password] --> [integration service certificate and key]
[server.ssl.truststore] --> keystore.jks
[server.ssl.truststore-password] --> keystore.jks
[ptai-backend-services.ptai-key-alias] --> [ptai ssl client certificate and key]
[ptai-backend-services.ptai-key-password] --> [ptai ssl client certificate and key]
[ptai-authorization-server.sign-key-alias] --> [embedded authz service certificate and key]
[ptai-authorization-server.sign-key-password] --> [embedded authz service certificate and key]
[ptai-integration-service.check-cert-alias] --> [embedded authz service certificate and key]
@enduml