@startuml

class Exception

class BaseClientException {
}

BaseClientException --> "inner" Exception

BaseClientException --|> RuntimeException
RuntimeException --|> Exception

JenkinsClientException --|> BaseClientException
JenkinsServerException --|> JenkinsClientException
PtaiClientException --|> BaseClientException
PtaiServerException --|> PtaiClientException

ApiException --|> Exception
Exception --|> Throwable

@enduml
