@startuml
skinparam ConditionEndStyle hline
start
note right
    During job creation following attributes are defined
    * jsonSettings
    * jsonPolicy
    * asynchronous
    * reports
end note
if (jsonSettings defined) then (true)
    if (verify jsonSettings) then (false)
        #pink:ERROR;
        kill
    else (true)
        :settings/
    endif
endif
if (jsonPolicy defined) then (true)
    if (verify jsonPolicy) then (false)
        #pink:ERROR;
        kill
    else (true)
        :policy/
    endif
endif
if (settings defined) then (true)
    :name = settings.getProjectName/
endif
:search project;
if (project found) then (true)
    if (settings defined) then (true)
        :setup scan settings from JSON;
    endif
else (false)
    if (settings defined) then (false)
        #pink:ERROR;
        kill
    else (true)
        :create project from JSON;
    endif
endif
:zip and upload sources;
:scanResultId = scan/
:scanStartedCallback>
note right
    Notify AstJob platform-specific
    implementation that code scan
    started so we need to setup SIGINT
    handler to call stop in case of termination
end note
:saveArtifact('result.url');
note right
    Save scan result
    endpoint URL to file
    to be able to access
    it later
end note
if (asynchronous) then (true)
    #lightgreen:SUCCESS;
    stop
endif

:state = waitForComplete;
:scanCompleteCallback>
note right
    Notify AstJob platform-specific
    implementation that code scan
    complete so there's no need to
    stop it if SIGINT recieved
end note
:stage = state.getProgress().getStage();
note right
    Possible stages after AST finished are:
    * DONE
    * FAILED
    * ABORTED
end note
if (stage is DONE or ABORTED and reports defined) then (true)
    :generate reports>
endif
if (stage is ABORTED) then (true)
    #pink:INTERRUPTED;
    stop
endif
if (policy REJECTED) then (true)
    if (FAIL-IF-FAILED) then(true)
        #pink:FAILED;
        stop
    endif
elseif (policy CONFIRMED) then(true)
        if (FAIL-IF-UNSTABLE and SCANERRORS) then(true)
            #pink:FAILED;
            stop
        endif
else
    if (FAIL-IF-UNSTABLE and SCANERRORS) then(true)
        #pink:FAILED;
        stop
    endif
endif
-> Policy not defined;
#lightgreen:SUCCESS;
stop
@enduml