@startuml
'https://plantuml.com/class-diagram

abstract class IssueBase {
    String type
}

class V36FingerprintIssue {
    String[] fingerprintIds
}
V36FingerprintIssue --|> IssueBase

/'
class V36VulnerabilityIssue
class V36WeaknessIssue
class V36UnknownIssue
class V36ConfigurationIssue
class V36BlackBoxIssue
class V36YaraMatchIssue
V36VulnerabilityIssue -right-|> IssueBase
V36WeaknessIssue -right-|> IssueBase
V36UnknownIssue -right-|> IssueBase
V36ConfigurationIssue -right-|> IssueBase
V36BlackBoxIssue -right-|> IssueBase
V36YaraMatchIssue -right-|> IssueBase
'/

class IssuesModel
IssuesModel *-- "issues" IssueBase

class DescriptionBaseValue {
    String html
    String header
    String description
}
class IssueDescriptionModel {
    String identity
    int issueType
}
IssuesModel *-- "descriptions" IssueDescriptionModel
IssueDescriptionModel -- "descriptionValue" DescriptionBaseValue
' IssueDescriptionModel ..  IssueType



class IssueBaseMetadata {
    String Key
    int IssueType
    int Level
}
' IssueBaseMetadata ..  IssueType
' IssueBaseMetadata ..  IssueLevel
IssuesModel *-up- "metadatas" IssueBaseMetadata

class V36FingerprintIssueMetadata {
}
V36FingerprintIssueMetadata --|> IssueBaseMetadata
/'
class V36VulnerabilityIssueMetadata
class V36WeaknessIssueMetadata
class V36UnknownIssueMetadata
class V36ConfigurationIssueMetadata
class V36BlackBoxIssueMetadata
class V36YaraMatchIssueMetadata
V36VulnerabilityIssueMetadata --|> IssueBaseMetadata
V36WeaknessIssueMetadata --|> IssueBaseMetadata
V36UnknownIssueMetadata --|> IssueBaseMetadata
V36ConfigurationIssueMetadata --|> IssueBaseMetadata
V36BlackBoxIssueMetadata --|> IssueBaseMetadata
V36YaraMatchIssueMetadata --|> IssueBaseMetadata
'/

enum IssueType {
    Unknown = 0
    Vulnerability = 1
    Weakness = 2
    Configuration = 3
    Fingerprint = 4
    BlackBox = 5
    YaraMatch = 6
}

enum IssueLevel {
    None = 0
    Potential = 10
    Low = 20
    Medium = 30
    High = 40
}

IssueBase::type .left. IssueDescriptionModel::identity
IssueBase::type .right. IssueBaseMetadata::Key
V36FingerprintIssue::fingerprintIds .. IssueDescriptionModel::identity
V36FingerprintIssue::fingerprintIds .. IssueBaseMetadata::Key


@enduml