@startuml
class BS.AbstractPasswordForm
class PtaiConnectionSettingsForm
class GlobalConnectionSettingsForm
class TaskConnectionSettingsForm
class TaskScanSettingsForm
class ReportSettingsForm

PtaiConnectionSettingsForm -up-|> BS.AbstractPasswordForm
GlobalConnectionSettingsForm -up-|> PtaiConnectionSettingsForm
TaskConnectionSettingsForm -up-|> PtaiConnectionSettingsForm
TaskScanSettingsForm -up-|> PtaiConnectionSettingsForm
ReportSettingsForm -up-|> PtaiConnectionSettingsForm

@enduml