@startuml
actor User
box "Teamcity" #B0E0F0
participant editRunType.html
participant editRunParams.jsp
end box
box "BS" #F0F0F0
participant EditBuildRunnerForm
participant PasswordFormSaver
participant FormSaver
participant AbstractPasswordForm
end box
box "PTAI" #FFE0E0
participant ptai.js
participant PtaiConnectionSettingsForm
participant AstEditRunTypeControllerExtension
participant AstSettingsPageController
end box
== Load page ==
User -> editRunType.html: GET
create EditBuildRunnerForm
editRunType.html -> EditBuildRunnerForm: new
editRunType.html -> EditBuildRunnerForm: setupEventHandlers
editRunType.html -> editRunParams.jsp: load
create ptai.js
editRunParams.jsp -> ptai.js: getScript
create PtaiConnectionSettingsForm
ptai.js -> PtaiConnectionSettingsForm : new
ptai.js -> PtaiConnectionSettingsForm : setupEventHandlers
== Page interaction ==
User -> editRunType.html: Click on UI control

editRunType.html -> EditBuildRunnerForm: updateState
activate EditBuildRunnerForm
EditBuildRunnerForm -> editRunType.html: POST
activate editRunType.html
editRunType.html -> AstEditRunTypeControllerExtension: updateState
deactivate editRunType.html
deactivate EditBuildRunnerForm

editRunType.html -> PtaiConnectionSettingsForm: updateState
activate PtaiConnectionSettingsForm
PtaiConnectionSettingsForm -> PtaiConnectionSettingsForm: modify
activate PtaiConnectionSettingsForm
PtaiConnectionSettingsForm -> PasswordFormSaver : save
PasswordFormSaver -> FormSaver : save
FormSaver --> AbstractPasswordForm : serializeParameters
note right
AbstractPasswordForm doesn't support passwordProperty but
passwordField only as it relies on getEncryptedPassword call
that passwordProperty is missing. So we need to implement
serializeParameters in AbstractPasswordForm descendant or
implement getEncryptedPassword for passwordProperty
end note
PtaiConnectionSettingsForm -> AstSettingsPageController: POST /ptai/ast.html


@enduml