@startuml
start
partition Initialization {
if (propertiesBean has value) then (true)
    :value = random();
    note right #EEEEEE
    Plugin provided bean with encrypted
    property. As that value too long to
    be shown in the password field we
    will simply generate unique random
    value that will help us to distinct
    if password was changed
    end note
else (false)
    :value = '';
endif
:field.value = value;
:hidden.encrypted = propertiesBean.getEncryptedPropertyValue(name);
note right #EEEEEE
May be empty if plugin
provided no data
end note
}
partition Run {
:password.onkeyup>
if (hidden.encrypted empty) then (false)
    if (field.value == value) then (false)
        :hidden.encrypted = '';
        stop
        note right #EEEEEE
        User changed existing encrypted
        password value so we need to reset
        hidden field
        end note
    else (true)
        stop
        note right #EEEEEE
        User pressed key but value not changed.
        I.e. something like Ctrl-C etc. No need
        to reset existing encrypted password value
        end note
    endif
else (true)
    stop
    note right #EEEEEE
    User pressed key. If plugin hasn't provided
    bean with existing encrypted password value
    there's no need to reset it
    end note
endif
}
@enduml