@startuml

class ScanInfo {
  +String scanDate
  +int TotalFileCount
  +int ScannedFileCount
  +int VulnerableFiles
  +int TotalVulnerabilityCount
  +int AcceptedVulnerabilities
  +int DiscardedVulnerabilities
  +int SuppressedVulnerabilities
  +int NewVulnerabilities
  +int PreviousVulnerabilities
  +int NonFilteredVulnerabilitiesCount
  +int NonFilteredAcceptedVulnerabilitiesCount
  +int NonFilteredDiscardedVulnerabilitiesCount
  +int NonFilteredSuppressedVulnerabilitiesCount
  +int NonFilteredNewVulnerabilitiesCount
  +int NonFilteredPreviousVulnerabilitiesCount
  +int PolicyState
}

class IncludedFilters {
  +String ConformationStatuses
}

class ExcludedFilters {
  +String SuspectedOrSecondOrder
}
ExcludedFilters --|> IncludedFilters

FilterInformation --> "includedFilters" IncludedFilters
FilterInformation --> "excludedFilters" ExcludedFilters

class Setting {
  +int order
  +boolean isExternalLink
}

ScanInfo --> "scanSettings[]" Setting
ScanInfo --> "filterInformation" FilterInformation

class BaseDisplayName {
  +String displayName
  +String value
}

class Level {
  +String severity
}
Level --|> BaseDisplayName

Nist --|> BaseDisplayName
Owasp --|> BaseDisplayName
Owaspm --|> BaseDisplayName
Pcidss --|> BaseDisplayName
Sans --|> BaseDisplayName

class Type {
  +String id
  +String groupId
}
Type --|> BaseDisplayName
Setting --|> BaseDisplayName

class Vulnerability {
  +boolean IsSuspected
  +boolean IsSecondOrder
  +boolean IsSuppressed
}

class IsPotential {
  +boolean value
}
class IsSuspected {
  +boolean value
}
class IsSecondOrder {
  +boolean value
}
class Function {
  +String value
}
class Entry {
  +String value
}
class NumberLine {
  +int value
}
class Exploit {
  +String value
}
class AutocheckExploit {
  +String value
}
class ModifyExploit {
  +String value
}
class TrimmedExploit {
  +String value
}
class TrimmedAutocheckExploit {
  +boolean value
}
class TrimmedFunction {
  +boolean value
}

class RawLine {
  +String value
}
class TrimmedRawLine {
  +String value
}
class Place {
  +String value
}
class AdditionalConditions {
  +String value
}
class TrimmedAdditionalConditions {
  +String value
}
class GraphId {
  +int value
}
class SourceFile {
  +String value
}
enum ScanModeType {
  FromPublicProtected
  FromEntryPoint
}
class ScanMode {
  +String value
}
class ScanModeId {
  +int value
}
class VulnerableCode {
  +String value
}
enum TypeKeyType {
  Vulnerability
  FingerprintVulnerability
  ConfigurationVulnerability
  PotentialVulnerability
}
class TypeKey {
  +TypeKeyType value
}
class GroupType {
  +int value
}
class IsSuppressed {
  +boolean value
}
class IsNew {
  +boolean value
}
class Id {
  +String value
}
class PrimaryFile {
  +String value
}
class Counter {
  +int value
}
class ApprovalState {
  +int value
}
class ApprovalStateId {
  +int value
}
class IsFavorite {
  +boolean value
}
class InspectionResultId {
  +int value
}
class Vuln
class CommonData
class DataFlow
class DataFlowElement {
  +String fileName
  +String fullPath
  +String entryType
  +String entryTypeDisplayValue
}

class CodeLine {
  +String lineType
  +int lineNumber
}
DataFlowElement --> CodeLine
class CodeLinePart {
  +String partType
  +String value
}
CodeLine --> CodeLinePart
DataFlow --> DataFlowElement

class Cwe
class ParentItem
ParentItem ..> Place

Vulnerability --> IsPotential
Vulnerability --> IsSecondOrder
Vulnerability --> Function
Vulnerability --> Entry
Vulnerability --> NumberLine
Vulnerability --> Exploit
Vulnerability --> AutocheckExploit
Vulnerability --> ModifyExploit
Vulnerability --> TrimmedExploit
Vulnerability --> TrimmedAutocheckExploit
Vulnerability --> TrimmedFunction
Vulnerability --> RawLine
Vulnerability --> TrimmedRawLine
Vulnerability --> Place
Vulnerability --> AdditionalConditions
Vulnerability --> TrimmedAdditionalConditions
Vulnerability --> GraphId
Vulnerability --> ScanMode
Vulnerability --> ScanModeId
Vulnerability --> VulnerableCode
Vulnerability --> DataFlow
Vulnerability --> Cwe

class BaseVulnerability
BaseVulnerability --> SourceFile
BaseVulnerability --> IsSuspected
BaseVulnerability --> TypeKey
BaseVulnerability --> IsSuppressed
BaseVulnerability --> GroupType
BaseVulnerability --> IsNew
BaseVulnerability --> Id
BaseVulnerability --> PrimaryFile
BaseVulnerability --> Counter
BaseVulnerability --> ApprovalState
BaseVulnerability --> Type
BaseVulnerability --> ApprovalStateId
BaseVulnerability --> IsFavorite
BaseVulnerability --> InspectionResultId
BaseVulnerability --> Vuln
BaseVulnerability --> CommonData
BaseVulnerability --> Level
BaseVulnerability --> ParentItem
BaseVulnerability --> Nist
BaseVulnerability --> Owasp
BaseVulnerability --> Owaspm
BaseVulnerability --> Pcidss
BaseVulnerability --> Sans

Vulnerability --|> BaseVulnerability
ConfVulnerability --|> BaseVulnerability
PMVulnerability --|> BaseVulnerability
FingerprintVulnerability --|> BaseVulnerability

FingerprintVulnerability --> Place
FingerprintVulnerability --> VulnerableCode
FingerprintVulnerability --> BinaryTitle
FingerprintVulnerability --> BinaryDescription
FingerprintVulnerability --> BinaryLevel
FingerprintVulnerability --> LocalizedDescription
FingerprintVulnerability --> Component

ConfVulnerability --|> NumberLine
ConfVulnerability --|> ExistingValue
ConfVulnerability --|> RecommendedValue
ConfVulnerability --|> Exploit
ConfVulnerability --|> RawLine
ConfVulnerability --|> Function
ConfVulnerability --|> Cwe

PMVulnerability --> MatchedCode
PMVulnerability --> "BeginLine" IntValue
PMVulnerability --> "BeginColumn" IntValue
PMVulnerability --> "EndLine" IntValue
PMVulnerability --> "EndColumn" IntValue
PMVulnerability --> "PatternId" IntValue
PMVulnerability --> "PatternKey" IntValue
PMVulnerability --> VulnerableCode
PMVulnerability --> BinaryTitle
PMVulnerability --> BinaryDescription
PMVulnerability --> BinaryLevel
PMVulnerability --> Cwe

class Report {
  +boolean haveGroups
}

Report --> ScanInfo
Report --> PMVulnerability
Report --> FingerprintVulnerability
Report --> ConfVulnerability
Report --> Vulnerability

@enduml
